### ISSUE TITLE
Hono + lucia-auth / luciaAuthCookieMiddleware is broken

### ISSUE THREAD

**Issue by aheissenberger** [vikejs/bati#341]
**Describe the bug**
luciaAuthCookieMiddleware deletes http header and return HTML as text.

This bug is specific to `hono` and does not exist when using `hattip` which suggest this is a problem in the `@universal-middleware/core`. 

**To Reproduce**
```
pnpm cli --react --hono --lucia-auth --react-lucia-auth
cd /tmp/bati-app
pnpm install
pnpm run dev
```

open http://localhost:3000/

**Expected behavior**

See a rendered startpage but get the HTML Code of the startpage

**Screenshots**

<img width="708" alt="SCR-20240821-upkx" src="https://github.com/user-attachments/assets/dbb04d03-3162-4f8a-8b2c-1822e3ae5a45">

Response Header:
```
HTTP/1.1 200 OK
cache-control: no-store, max-age=0
content-type: text/plain; charset=UTF-8
Date: Wed, 21 Aug 2024 21:56:18 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```

if you comment out this line `app.use(createMiddleware(luciaAuthCookieMiddleware)());` in `hono-entry.ts` the rendering is working again.

It looks like this is a problem specific with the feature in `@universal-middleware/core` to **manipulate the response object** and the wrapper for `hono`.

**Comment by magne4000** [comment]
Thanks for all the details, I'm on it!
