### ISSUE TITLE
`Try me in Stackblitz` button doesn't use selected package manager

### ISSUE THREAD

**Issue by rtritto** [vikejs/bati#358]
**Describe the bug**
The Stackblitz page doesn't use related pacakge manager (_pnpm_ is always used).

**To Reproduce**
- select a package manager (choose one different from _pnpm_)
- click the `Try me in Stackblitz` button

**Expected behavior**
Selected package manager is used on Stackblitz page

**Screenshots**
![immagine](https://github.com/user-attachments/assets/217220b8-99e2-4e4d-ac0b-a77a6e1aed8d)

**Comment by rtritto** [comment]
> `bun` is not supported by Stackblitz

Bun can be installed using a package manager as dev dependency (eg `yarn add -D bun`)
Then you can run bun using the package manager with scripts in _package.json_ (eg `"start": "bun --bun vite"`)
Related #366

---

> yarn is old (v1 and not v4)

Yarn v4 can be installed using `yarn set version berry`

---

Imo, an user should be free to use a different package manager instead of `pnpm`.

**Comment by magne4000** [comment]
> Imo, an user should be free to use a different package manager instead of pnpm.

I'm perhaps not aware of how people are actually using Stackblitz.
Are you using it as an actual development platform, compared to only for testing purpose?

**Comment by rtritto** [comment]
In Stackblitz, you can test or fork but it's boring change (manually) a package manager when the CLI can automatically do and save time.

**Comment by magne4000** [comment]
I see, let met check what I can do

**Comment by magne4000** [comment]
No chance sadly.

### yarn
```
❯ yarn set version berry
warning package.json: No license field
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

### bun
Installing as a `devDependency` works, but the install binary is unusable.


Did you manage to have `yarn@v4` or `bun` working in Stackblitz yourself ?

**Comment by rtritto** [comment]
> ### yarn
> 
> ```
> ❯ yarn set version berry
> warning package.json: No license field
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> error An unexpected error occurred: "https://github.com/yarnpkg/berry/raw/master/packages/yarnpkg-cli/bin/yarn.js: socket hang up"
> ```
> 
> ### bun
> 
> Installing as a `devDependency` works, but the installed binary is unusable.



You're right.
Currently for `yarn` only v1 is supported (https://github.com/stackblitz/webcontainer-core/issues/1235).

> Did you manage to have yarn@v4 or bun working in Stackblitz yourself ?

No

---

So, currently, can be implented only the CLI for `npm` and `yarn` (v1) or (maybe) change the platfprm (idk).

Thanks, anyway.

**Comment by magne4000** [comment]
Right now, I'll stick with `pnpm` only, as the Stackblitz button is mainly here for testing purpose.
