### ISSUE TITLE
feat: remove empty global.d.ts

### ISSUE THREAD

**Issue by magne4000** [vikejs/bati#389]
If `global.d.ts` is empty, remove it. Also make sure that comments are properly merged.

**Comment by firxworx** [comment]
Noting related issue: in my case `global.d.ts` was not empty but there is a useless empty export at the end of it `export {}`. 

The empty export will also get flagged as an issue by biome: biome[lint/complexity/noUselessEmptyExport](https://biomejs.dev/linter/rules/no-useless-empty-export)

**Comment by magne4000** [comment]
> Noting related issue: in my case `global.d.ts` was not empty but there is a useless empty export at the end of it `export {}`.
> 
> The empty export will also get flagged as an issue by biome: biome[lint/complexity/noUselessEmptyExport](https://biomejs.dev/linter/rules/no-useless-empty-export)

Do you remember which Bati flags you were having this issue with?

**Comment by magne4000** [comment]
> > Noting related issue: in my case `global.d.ts` was not empty but there is a useless empty export at the end of it `export {}`.
> > The empty export will also get flagged as an issue by biome: biome[lint/complexity/noUselessEmptyExport](https://biomejs.dev/linter/rules/no-useless-empty-export)
> 
> Do you remember which Bati flags you were having this issue with?

`pnpm create bati --react --express --biome` does it
