### ISSUE TITLE
Preact Support

### ISSUE THREAD

**Issue by rhildred** [vikejs/bati#423]
Would you please add preact to bati?

I am writing microfrontends using fastapi and plain javascript for the custom element. I would prefer to have a fullstack typescript solution that I can serve from cloudflare pages. I would like to use preact-custom-element and hono for the microservice. 

I got most of the way there with https://github.com/brillout/vike-preact. I was super excited because I could use vike and mdx for my api documentation by just hacking the demo a little. Unfortunately i failed when i tried to add hono in and ran out of time.

I think that microfrontends are a great application for vike. Vike is great for the documentation and cloudflare/hono is great for backends like stripe/square .... I feel that i will have more cycles in a few weeks to get it working. If you would please get preact in bati, I could move on to the preact-custom-element piece.

**Comment by magne4000** [comment]
Closing in favor of #362
